"""Add pending_deletion to conversations

Revision ID: 0003_add_pending_deletion
Revises: d939d6394508
Create Date: 2025-12-17 20:06:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_add_pending_deletion'
down_revision: Union[str, None] = 'd939d6394508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('pending_deletion', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'pending_deletion')
    # ### end Alembic commands ###
