"""Add detected_language to paragraphs

Revision ID: 08bfb0e5cec0
Revises: d939d6394508
Create Date: 2025-12-17 19:16:37.807470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bfb0e5cec0'
down_revision: Union[str, None] = 'd939d6394508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paragraphs', sa.Column('detected_language', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paragraphs', 'detected_language')
    # ### end Alembic commands ###
