"""
Supported languages configuration.
"""

QWEN_SUPPORTED_LANGUAGES = [
    {"code": "af", "name": "Afrikaans"},
    {"code": "am", "name": "Amharic"},
    {"code": "ar", "name": "Arabic"},
    {"code": "as", "name": "Assamese"},
    {"code": "az", "name": "Azerbaijani"},
    {"code": "ba", "name": "Bashkir"},
    {"code": "be", "name": "Belarusian"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "bn", "name": "Bengali"},
    {"code": "bo", "name": "Tibetan"},
    {"code": "br", "name": "Breton"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "ca", "name": "Catalan"},
    {"code": "cs", "name": "Czech"},
    {"code": "cy", "name": "Welsh"},
    {"code": "da", "name": "Danish"},
    {"code": "de", "name": "German"},
    {"code": "el", "name": "Greek"},
    {"code": "en", "name": "English"},
    {"code": "es", "name": "Spanish"},
    {"code": "et", "name": "Estonian"},
    {"code": "eu", "name": "Basque"},
    {"code": "fa", "name": "Persian"},
    {"code": "fi", "name": "Finnish"},
    {"code": "fo", "name": "Faroese"},
    {"code": "fr", "name": "French"},
    {"code": "gl", "name": "Galician"},
    {"code": "gu", "name": "Gujarati"},
    {"code": "ha", "name": "Hausa"},
    {"code": "haw", "name": "Hawaiian"},
    {"code": "he", "name": "Hebrew"},
    {"code": "hi", "name": "Hindi"},
    {"code": "hr", "name": "Croatian"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "hy", "name": "Armenian"},
    {"code": "id", "name": "Indonesian"},
    {"code": "is", "name": "Icelandic"},
    {"code": "it", "name": "Italian"},
    {"code": "ja", "name": "Japanese"},
    {"code": "ka", "name": "Georgian"},
    {"code": "kk", "name": "Kazakh"},
    {"code": "km", "name": "Khmer"},
    {"code": "kn", "name": "Kannada"},
    {"code": "ko", "name": "Korean"},
    {"code": "lo", "name": "Lao"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "lv", "name": "Latvian"},
    {"code": "mg", "name": "Malagasy"},
    {"code": "mi", "name": "Maori"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "ml", "name": "Malayalam"},
    {"code": "mn", "name": "Mongolian"},
    {"code": "mr", "name": "Marathi"},
    {"code": "ms", "name": "Malay"},
    {"code": "mt", "name": "Maltese"},
    {"code": "my", "name": "Burmese"},
    {"code": "ne", "name": "Nepali"},
    {"code": "nl", "name": "Dutch"},
    {"code": "no", "name": "Norwegian"},
    {"code": "oc", "name": "Occitan"},
    {"code": "pa", "name": "Punjabi"},
    {"code": "pl", "name": "Polish"},
    {"code": "ps", "name": "Pashto"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "ro", "name": "Romanian"},
    {"code": "ru", "name": "Russian"},
    {"code": "sa", "name": "Sanskrit"},
    {"code": "sd", "name": "Sindhi"},
    {"code": "si", "name": "Sinhala"},
    {"code": "sk", "name": "Slovak"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "sn", "name": "Shona"},
    {"code": "so", "name": "Somali"},
    {"code": "sq", "name": "Albanian"},
    {"code": "sr", "name": "Serbian"},
    {"code": "su", "name": "Sundanese"},
    {"code": "sv", "name": "Swedish"},
    {"code": "sw", "name": "Swahili"},
    {"code": "ta", "name": "Tamil"},
    {"code": "te", "name": "Telugu"},
    {"code": "tg", "name": "Tajik"},
    {"code": "th", "name": "Thai"},
    {"code": "tl", "name": "Filipino"},
    {"code": "tr", "name": "Turkish"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "ur", "name": "Urdu"},
    {"code": "uz", "name": "Uzbek"},
    {"code": "vi", "name": "Vietnamese"},
    {"code": "yi", "name": "Yiddish"},
    {"code": "yo", "name": "Yoruba"},
    {"code": "yue", "name": "Cantonese"},
    {"code": "zh", "name": "Chinese"},
    {"code": "ht", "name": "Haitian Creole"},
    {"code": "jw", "name": "Javanese"},
    {"code": "la", "name": "Latin"},
    {"code": "lb", "name": "Luxembourgish"},
    {"code": "ln", "name": "Lingala"},
    {"code": "nn", "name": "Norwegian Nynorsk"},
    {"code": "tk", "name": "Turkmen"},
    {"code": "tt", "name": "Tatar"},
]

TRANSLATEGEMMA_RAW_LANGUAGES = [
    {"code": "aa", "name": "Afar"},
    {"code": "aa-DJ", "name": "Afar"},
    {"code": "aa-ER", "name": "Afar"},
    {"code": "ab", "name": "Abkhazian"},
    {"code": "af", "name": "Afrikaans"},
    {"code": "af-NA", "name": "Afrikaans"},
    {"code": "ak", "name": "Akan"},
    {"code": "am", "name": "Amharic"},
    {"code": "an", "name": "Aragonese"},
    {"code": "ar", "name": "Arabic"},
    {"code": "ar-AE", "name": "Arabic"},
    {"code": "ar-BH", "name": "Arabic"},
    {"code": "ar-DJ", "name": "Arabic"},
    {"code": "ar-DZ", "name": "Arabic"},
    {"code": "ar-EG", "name": "Arabic"},
    {"code": "ar-EH", "name": "Arabic"},
    {"code": "ar-ER", "name": "Arabic"},
    {"code": "ar-IL", "name": "Arabic"},
    {"code": "ar-IQ", "name": "Arabic"},
    {"code": "ar-JO", "name": "Arabic"},
    {"code": "ar-KM", "name": "Arabic"},
    {"code": "ar-KW", "name": "Arabic"},
    {"code": "ar-LB", "name": "Arabic"},
    {"code": "ar-LY", "name": "Arabic"},
    {"code": "ar-MA", "name": "Arabic"},
    {"code": "ar-MR", "name": "Arabic"},
    {"code": "ar-OM", "name": "Arabic"},
    {"code": "ar-PS", "name": "Arabic"},
    {"code": "ar-QA", "name": "Arabic"},
    {"code": "ar-SA", "name": "Arabic"},
    {"code": "ar-SD", "name": "Arabic"},
    {"code": "ar-SO", "name": "Arabic"},
    {"code": "ar-SS", "name": "Arabic"},
    {"code": "ar-SY", "name": "Arabic"},
    {"code": "ar-TD", "name": "Arabic"},
    {"code": "ar-TN", "name": "Arabic"},
    {"code": "ar-YE", "name": "Arabic"},
    {"code": "as", "name": "Assamese"},
    {"code": "az", "name": "Azerbaijani"},
    {"code": "az-Arab", "name": "Azerbaijani"},
    {"code": "az-Arab-IQ", "name": "Azerbaijani"},
    {"code": "az-Arab-TR", "name": "Azerbaijani"},
    {"code": "az-Cyrl", "name": "Azerbaijani"},
    {"code": "az-Latn", "name": "Azerbaijani"},
    {"code": "ba", "name": "Bashkir"},
    {"code": "be", "name": "Belarusian"},
    {"code": "be-tarask", "name": "Belarusian"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "bg-BG", "name": "Bulgarian"},
    {"code": "bm", "name": "Bambara"},
    {"code": "bm-Nkoo", "name": "Bambara"},
    {"code": "bn", "name": "Bengali"},
    {"code": "bn-IN", "name": "Bengali"},
    {"code": "bo", "name": "Tibetan"},
    {"code": "bo-IN", "name": "Tibetan"},
    {"code": "br", "name": "Breton"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "bs-Cyrl", "name": "Bosnian"},
    {"code": "bs-Latn", "name": "Bosnian"},
    {"code": "ca", "name": "Catalan"},
    {"code": "ca-AD", "name": "Catalan"},
    {"code": "ca-ES", "name": "Catalan"},
    {"code": "ca-FR", "name": "Catalan"},
    {"code": "ca-IT", "name": "Catalan"},
    {"code": "ce", "name": "Chechen"},
    {"code": "co", "name": "Corsican"},
    {"code": "cs", "name": "Czech"},
    {"code": "cs-CZ", "name": "Czech"},
    {"code": "cv", "name": "Chuvash"},
    {"code": "cy", "name": "Welsh"},
    {"code": "da", "name": "Danish"},
    {"code": "da-DK", "name": "Danish"},
    {"code": "da-GL", "name": "Danish"},
    {"code": "de", "name": "German"},
    {"code": "de-AT", "name": "German"},
    {"code": "de-BE", "name": "German"},
    {"code": "de-CH", "name": "German"},
    {"code": "de-DE", "name": "German"},
    {"code": "de-IT", "name": "German"},
    {"code": "de-LI", "name": "German"},
    {"code": "de-LU", "name": "German"},
    {"code": "dv", "name": "Divehi"},
    {"code": "dz", "name": "Dzongkha"},
    {"code": "ee", "name": "Ewe"},
    {"code": "ee-TG", "name": "Ewe"},
    {"code": "el", "name": "Greek"},
    {"code": "el-CY", "name": "Greek"},
    {"code": "el-GR", "name": "Greek"},
    {"code": "el-polyton", "name": "Greek"},
    {"code": "en", "name": "English"},
    {"code": "en-AE", "name": "English"},
    {"code": "en-AG", "name": "English"},
    {"code": "en-AI", "name": "English"},
    {"code": "en-AS", "name": "English"},
    {"code": "en-AT", "name": "English"},
    {"code": "en-AU", "name": "English"},
    {"code": "en-BB", "name": "English"},
    {"code": "en-BE", "name": "English"},
    {"code": "en-BI", "name": "English"},
    {"code": "en-BM", "name": "English"},
    {"code": "en-BS", "name": "English"},
    {"code": "en-BW", "name": "English"},
    {"code": "en-BZ", "name": "English"},
    {"code": "en-CA", "name": "English"},
    {"code": "en-CC", "name": "English"},
    {"code": "en-CH", "name": "English"},
    {"code": "en-CK", "name": "English"},
    {"code": "en-CM", "name": "English"},
    {"code": "en-CX", "name": "English"},
    {"code": "en-CY", "name": "English"},
    {"code": "en-CZ", "name": "English"},
    {"code": "en-DE", "name": "English"},
    {"code": "en-DG", "name": "English"},
    {"code": "en-DK", "name": "English"},
    {"code": "en-DM", "name": "English"},
    {"code": "en-ER", "name": "English"},
    {"code": "en-ES", "name": "English"},
    {"code": "en-FI", "name": "English"},
    {"code": "en-FJ", "name": "English"},
    {"code": "en-FK", "name": "English"},
    {"code": "en-FM", "name": "English"},
    {"code": "en-FR", "name": "English"},
    {"code": "en-GB", "name": "English"},
    {"code": "en-GD", "name": "English"},
    {"code": "en-GG", "name": "English"},
    {"code": "en-GH", "name": "English"},
    {"code": "en-GI", "name": "English"},
    {"code": "en-GM", "name": "English"},
    {"code": "en-GS", "name": "English"},
    {"code": "en-GU", "name": "English"},
    {"code": "en-GY", "name": "English"},
    {"code": "en-HK", "name": "English"},
    {"code": "en-HU", "name": "English"},
    {"code": "en-ID", "name": "English"},
    {"code": "en-IE", "name": "English"},
    {"code": "en-IL", "name": "English"},
    {"code": "en-IM", "name": "English"},
    {"code": "en-IN", "name": "English"},
    {"code": "en-IO", "name": "English"},
    {"code": "en-IT", "name": "English"},
    {"code": "en-JE", "name": "English"},
    {"code": "en-JM", "name": "English"},
    {"code": "en-KE", "name": "English"},
    {"code": "en-KI", "name": "English"},
    {"code": "en-KN", "name": "English"},
    {"code": "en-KY", "name": "English"},
    {"code": "en-LC", "name": "English"},
    {"code": "en-LR", "name": "English"},
    {"code": "en-LS", "name": "English"},
    {"code": "en-MG", "name": "English"},
    {"code": "en-MH", "name": "English"},
    {"code": "en-MO", "name": "English"},
    {"code": "en-MP", "name": "English"},
    {"code": "en-MS", "name": "English"},
    {"code": "en-MT", "name": "English"},
    {"code": "en-MU", "name": "English"},
    {"code": "en-MV", "name": "English"},
    {"code": "en-MW", "name": "English"},
    {"code": "en-MY", "name": "English"},
    {"code": "en-NA", "name": "English"},
    {"code": "en-NF", "name": "English"},
    {"code": "en-NG", "name": "English"},
    {"code": "en-NL", "name": "English"},
    {"code": "en-NO", "name": "English"},
    {"code": "en-NR", "name": "English"},
    {"code": "en-NU", "name": "English"},
    {"code": "en-NZ", "name": "English"},
    {"code": "en-PG", "name": "English"},
    {"code": "en-PH", "name": "English"},
    {"code": "en-PK", "name": "English"},
    {"code": "en-PL", "name": "English"},
    {"code": "en-PN", "name": "English"},
    {"code": "en-PR", "name": "English"},
    {"code": "en-PT", "name": "English"},
    {"code": "en-PW", "name": "English"},
    {"code": "en-RO", "name": "English"},
    {"code": "en-RW", "name": "English"},
    {"code": "en-SB", "name": "English"},
    {"code": "en-SC", "name": "English"},
    {"code": "en-SD", "name": "English"},
    {"code": "en-SE", "name": "English"},
    {"code": "en-SG", "name": "English"},
    {"code": "en-SH", "name": "English"},
    {"code": "en-SI", "name": "English"},
    {"code": "en-SK", "name": "English"},
    {"code": "en-SL", "name": "English"},
    {"code": "en-SS", "name": "English"},
    {"code": "en-SX", "name": "English"},
    {"code": "en-SZ", "name": "English"},
    {"code": "en-TC", "name": "English"},
    {"code": "en-TK", "name": "English"},
    {"code": "en-TO", "name": "English"},
    {"code": "en-TT", "name": "English"},
    {"code": "en-TV", "name": "English"},
    {"code": "en-TZ", "name": "English"},
    {"code": "en-UG", "name": "English"},
    {"code": "en-UM", "name": "English"},
    {"code": "en-VC", "name": "English"},
    {"code": "en-VG", "name": "English"},
    {"code": "en-VI", "name": "English"},
    {"code": "en-VU", "name": "English"},
    {"code": "en-WS", "name": "English"},
    {"code": "en-ZA", "name": "English"},
    {"code": "en-ZM", "name": "English"},
    {"code": "en-ZW", "name": "English"},
    {"code": "eo", "name": "Esperanto"},
    {"code": "es", "name": "Spanish"},
    {"code": "es-AR", "name": "Spanish"},
    {"code": "es-BO", "name": "Spanish"},
    {"code": "es-BR", "name": "Spanish"},
    {"code": "es-BZ", "name": "Spanish"},
    {"code": "es-CL", "name": "Spanish"},
    {"code": "es-CO", "name": "Spanish"},
    {"code": "es-CR", "name": "Spanish"},
    {"code": "es-CU", "name": "Spanish"},
    {"code": "es-DO", "name": "Spanish"},
    {"code": "es-EA", "name": "Spanish"},
    {"code": "es-EC", "name": "Spanish"},
    {"code": "es-ES", "name": "Spanish"},
    {"code": "es-GQ", "name": "Spanish"},
    {"code": "es-GT", "name": "Spanish"},
    {"code": "es-HN", "name": "Spanish"},
    {"code": "es-IC", "name": "Spanish"},
    {"code": "es-MX", "name": "Spanish"},
    {"code": "es-NI", "name": "Spanish"},
    {"code": "es-PA", "name": "Spanish"},
    {"code": "es-PE", "name": "Spanish"},
    {"code": "es-PH", "name": "Spanish"},
    {"code": "es-PR", "name": "Spanish"},
    {"code": "es-PY", "name": "Spanish"},
    {"code": "es-SV", "name": "Spanish"},
    {"code": "es-US", "name": "Spanish"},
    {"code": "es-UY", "name": "Spanish"},
    {"code": "es-VE", "name": "Spanish"},
    {"code": "et", "name": "Estonian"},
    {"code": "et-EE", "name": "Estonian"},
    {"code": "eu", "name": "Basque"},
    {"code": "fa", "name": "Persian"},
    {"code": "fa-AF", "name": "Persian"},
    {"code": "fa-IR", "name": "Persian"},
    {"code": "ff", "name": "Fulah"},
    {"code": "ff-Adlm", "name": "Fulah"},
    {"code": "ff-Adlm-BF", "name": "Fulah"},
    {"code": "ff-Adlm-CM", "name": "Fulah"},
    {"code": "ff-Adlm-GH", "name": "Fulah"},
    {"code": "ff-Adlm-GM", "name": "Fulah"},
    {"code": "ff-Adlm-GW", "name": "Fulah"},
    {"code": "ff-Adlm-LR", "name": "Fulah"},
    {"code": "ff-Adlm-MR", "name": "Fulah"},
    {"code": "ff-Adlm-NE", "name": "Fulah"},
    {"code": "ff-Adlm-NG", "name": "Fulah"},
    {"code": "ff-Adlm-SL", "name": "Fulah"},
    {"code": "ff-Adlm-SN", "name": "Fulah"},
    {"code": "ff-Latn", "name": "Fulah"},
    {"code": "ff-Latn-BF", "name": "Fulah"},
    {"code": "ff-Latn-CM", "name": "Fulah"},
    {"code": "ff-Latn-GH", "name": "Fulah"},
    {"code": "ff-Latn-GM", "name": "Fulah"},
    {"code": "ff-Latn-GN", "name": "Fulah"},
    {"code": "ff-Latn-GW", "name": "Fulah"},
    {"code": "ff-Latn-LR", "name": "Fulah"},
    {"code": "ff-Latn-MR", "name": "Fulah"},
    {"code": "ff-Latn-NE", "name": "Fulah"},
    {"code": "ff-Latn-NG", "name": "Fulah"},
    {"code": "ff-Latn-SL", "name": "Fulah"},
    {"code": "fi", "name": "Finnish"},
    {"code": "fi-FI", "name": "Finnish"},
    {"code": "fil-PH", "name": "Filipino"},
    {"code": "fo", "name": "Faroese"},
    {"code": "fo-DK", "name": "Faroese"},
    {"code": "fr", "name": "French"},
    {"code": "fr-BE", "name": "French"},
    {"code": "fr-BF", "name": "French"},
    {"code": "fr-BI", "name": "French"},
    {"code": "fr-BJ", "name": "French"},
    {"code": "fr-BL", "name": "French"},
    {"code": "fr-CA", "name": "French"},
    {"code": "fr-CD", "name": "French"},
    {"code": "fr-CF", "name": "French"},
    {"code": "fr-CG", "name": "French"},
    {"code": "fr-CH", "name": "French"},
    {"code": "fr-CI", "name": "French"},
    {"code": "fr-CM", "name": "French"},
    {"code": "fr-DJ", "name": "French"},
    {"code": "fr-DZ", "name": "French"},
    {"code": "fr-FR", "name": "French"},
    {"code": "fr-GA", "name": "French"},
    {"code": "fr-GF", "name": "French"},
    {"code": "fr-GN", "name": "French"},
    {"code": "fr-GP", "name": "French"},
    {"code": "fr-GQ", "name": "French"},
    {"code": "fr-HT", "name": "French"},
    {"code": "fr-KM", "name": "French"},
    {"code": "fr-LU", "name": "French"},
    {"code": "fr-MA", "name": "French"},
    {"code": "fr-MC", "name": "French"},
    {"code": "fr-MF", "name": "French"},
    {"code": "fr-MG", "name": "French"},
    {"code": "fr-ML", "name": "French"},
    {"code": "fr-MQ", "name": "French"},
    {"code": "fr-MR", "name": "French"},
    {"code": "fr-MU", "name": "French"},
    {"code": "fr-NC", "name": "French"},
    {"code": "fr-NE", "name": "French"},
    {"code": "fr-PF", "name": "French"},
    {"code": "fr-PM", "name": "French"},
    {"code": "fr-RE", "name": "French"},
    {"code": "fr-RW", "name": "French"},
    {"code": "fr-SC", "name": "French"},
    {"code": "fr-SN", "name": "French"},
    {"code": "fr-SY", "name": "French"},
    {"code": "fr-TD", "name": "French"},
    {"code": "fr-TG", "name": "French"},
    {"code": "fr-TN", "name": "French"},
    {"code": "fr-VU", "name": "French"},
    {"code": "fr-WF", "name": "French"},
    {"code": "fr-YT", "name": "French"},
    {"code": "fy", "name": "Western Frisian"},
    {"code": "ga", "name": "Irish"},
    {"code": "ga-GB", "name": "Irish"},
    {"code": "gd", "name": "Scottish Gaelic"},
    {"code": "gl", "name": "Galician"},
    {"code": "gn", "name": "Guarani"},
    {"code": "gu", "name": "Gujarati"},
    {"code": "gu-IN", "name": "Gujarati"},
    {"code": "gv", "name": "Manx"},
    {"code": "ha", "name": "Hausa"},
    {"code": "ha-Arab", "name": "Hausa"},
    {"code": "ha-Arab-SD", "name": "Hausa"},
    {"code": "ha-GH", "name": "Hausa"},
    {"code": "ha-NE", "name": "Hausa"},
    {"code": "he", "name": "Hebrew"},
    {"code": "he-IL", "name": "Hebrew"},
    {"code": "hi", "name": "Hindi"},
    {"code": "hi-IN", "name": "Hindi"},
    {"code": "hi-Latn", "name": "Hindi"},
    {"code": "hr", "name": "Croatian"},
    {"code": "hr-BA", "name": "Croatian"},
    {"code": "hr-HR", "name": "Croatian"},
    {"code": "ht", "name": "Haitian"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "hu-HU", "name": "Hungarian"},
    {"code": "hy", "name": "Armenian"},
    {"code": "ia", "name": "Interlingua"},
    {"code": "id", "name": "Indonesian"},
    {"code": "id-ID", "name": "Indonesian"},
    {"code": "ie", "name": "Interlingue"},
    {"code": "ig", "name": "Igbo"},
    {"code": "ii", "name": "Sichuan Yi"},
    {"code": "ik", "name": "Inupiaq"},
    {"code": "io", "name": "Ido"},
    {"code": "is", "name": "Icelandic"},
    {"code": "it", "name": "Italian"},
    {"code": "it-CH", "name": "Italian"},
    {"code": "it-IT", "name": "Italian"},
    {"code": "it-SM", "name": "Italian"},
    {"code": "it-VA", "name": "Italian"},
    {"code": "iu", "name": "Inuktitut"},
    {"code": "iu-Latn", "name": "Inuktitut"},
    {"code": "ja", "name": "Japanese"},
    {"code": "ja-JP", "name": "Japanese"},
    {"code": "jv", "name": "Javanese"},
    {"code": "ka", "name": "Georgian"},
    {"code": "ki", "name": "Kikuyu"},
    {"code": "kk", "name": "Kazakh"},
    {"code": "kk-Arab", "name": "Kazakh"},
    {"code": "kk-Cyrl", "name": "Kazakh"},
    {"code": "kk-KZ", "name": "Kazakh"},
    {"code": "kl", "name": "Kalaallisut"},
    {"code": "km", "name": "Central Khmer"},
    {"code": "kn", "name": "Kannada"},
    {"code": "kn-IN", "name": "Kannada"},
    {"code": "ko", "name": "Korean"},
    {"code": "ko-CN", "name": "Korean"},
    {"code": "ko-KP", "name": "Korean"},
    {"code": "ko-KR", "name": "Korean"},
    {"code": "ks", "name": "Kashmiri"},
    {"code": "ks-Arab", "name": "Kashmiri"},
    {"code": "ks-Deva", "name": "Kashmiri"},
    {"code": "ku", "name": "Kurdish"},
    {"code": "kw", "name": "Cornish"},
    {"code": "ky", "name": "Kyrgyz"},
    {"code": "la", "name": "Latin"},
    {"code": "lb", "name": "Luxembourgish"},
    {"code": "lg", "name": "Ganda"},
    {"code": "ln", "name": "Lingala"},
    {"code": "ln-AO", "name": "Lingala"},
    {"code": "ln-CF", "name": "Lingala"},
    {"code": "ln-CG", "name": "Lingala"},
    {"code": "lo", "name": "Lao"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "lt-LT", "name": "Lithuanian"},
    {"code": "lu", "name": "Luba-Katanga"},
    {"code": "lv", "name": "Latvian"},
    {"code": "lv-LV", "name": "Latvian"},
    {"code": "mg", "name": "Malagasy"},
    {"code": "mi", "name": "Maori"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "ml", "name": "Malayalam"},
    {"code": "ml-IN", "name": "Malayalam"},
    {"code": "mn", "name": "Mongolian"},
    {"code": "mn-Mong", "name": "Mongolian"},
    {"code": "mn-Mong-MN", "name": "Mongolian"},
    {"code": "mr", "name": "Marathi"},
    {"code": "mr-IN", "name": "Marathi"},
    {"code": "ms", "name": "Malay"},
    {"code": "ms-Arab", "name": "Malay"},
    {"code": "ms-Arab-BN", "name": "Malay"},
    {"code": "ms-BN", "name": "Malay"},
    {"code": "ms-ID", "name": "Malay"},
    {"code": "ms-SG", "name": "Malay"},
    {"code": "mt", "name": "Maltese"},
    {"code": "my", "name": "Burmese"},
    {"code": "nb", "name": "Norwegian Bokmål"},
    {"code": "nb-SJ", "name": "Norwegian Bokmål"},
    {"code": "nd", "name": "North Ndebele"},
    {"code": "ne", "name": "Nepali"},
    {"code": "ne-IN", "name": "Nepali"},
    {"code": "nl", "name": "Dutch"},
    {"code": "nl-AW", "name": "Dutch"},
    {"code": "nl-BE", "name": "Dutch"},
    {"code": "nl-BQ", "name": "Dutch"},
    {"code": "nl-CW", "name": "Dutch"},
    {"code": "nl-NL", "name": "Dutch"},
    {"code": "nl-SR", "name": "Dutch"},
    {"code": "nl-SX", "name": "Dutch"},
    {"code": "nn", "name": "Norwegian Nynorsk"},
    {"code": "no", "name": "Norwegian"},
    {"code": "no-NO", "name": "Norwegian"},
    {"code": "nr", "name": "South Ndebele"},
    {"code": "nv", "name": "Navajo"},
    {"code": "ny", "name": "Chichewa"},
    {"code": "oc", "name": "Occitan"},
    {"code": "oc-ES", "name": "Occitan"},
    {"code": "om", "name": "Oromo"},
    {"code": "om-KE", "name": "Oromo"},
    {"code": "or", "name": "Oriya"},
    {"code": "os", "name": "Ossetian"},
    {"code": "os-RU", "name": "Ossetian"},
    {"code": "pa", "name": "Punjabi"},
    {"code": "pa-IN", "name": "Punjabi"},
    {"code": "pa-Arab", "name": "Punjabi"},
    {"code": "pa-Guru", "name": "Punjabi"},
    {"code": "pl", "name": "Polish"},
    {"code": "pl-PL", "name": "Polish"},
    {"code": "ps", "name": "Pashto"},
    {"code": "ps-PK", "name": "Pashto"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "pt-AO", "name": "Portuguese"},
    {"code": "pt-BR", "name": "Portuguese"},
    {"code": "pt-CH", "name": "Portuguese"},
    {"code": "pt-CV", "name": "Portuguese"},
    {"code": "pt-GQ", "name": "Portuguese"},
    {"code": "pt-GW", "name": "Portuguese"},
    {"code": "pt-LU", "name": "Portuguese"},
    {"code": "pt-MO", "name": "Portuguese"},
    {"code": "pt-MZ", "name": "Portuguese"},
    {"code": "pt-PT", "name": "Portuguese"},
    {"code": "pt-ST", "name": "Portuguese"},
    {"code": "pt-TL", "name": "Portuguese"},
    {"code": "qu", "name": "Quechua"},
    {"code": "qu-BO", "name": "Quechua"},
    {"code": "qu-EC", "name": "Quechua"},
    {"code": "rm", "name": "Romansh"},
    {"code": "rn", "name": "Rundi"},
    {"code": "ro", "name": "Romanian"},
    {"code": "ro-MD", "name": "Romanian"},
    {"code": "ro-RO", "name": "Romanian"},
    {"code": "ru", "name": "Russian"},
    {"code": "ru-BY", "name": "Russian"},
    {"code": "ru-KG", "name": "Russian"},
    {"code": "ru-KZ", "name": "Russian"},
    {"code": "ru-MD", "name": "Russian"},
    {"code": "ru-RU", "name": "Russian"},
    {"code": "ru-UA", "name": "Russian"},
    {"code": "rw", "name": "Kinyarwanda"},
    {"code": "sa", "name": "Sanskrit"},
    {"code": "sc", "name": "Sardinian"},
    {"code": "sd", "name": "Sindhi"},
    {"code": "sd-Arab", "name": "Sindhi"},
    {"code": "sd-Deva", "name": "Sindhi"},
    {"code": "se", "name": "Northern Sami"},
    {"code": "se-FI", "name": "Northern Sami"},
    {"code": "se-SE", "name": "Northern Sami"},
    {"code": "sg", "name": "Sango"},
    {"code": "si", "name": "Sinhala"},
    {"code": "sk", "name": "Slovak"},
    {"code": "sk-SK", "name": "Slovak"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "sl-SI", "name": "Slovenian"},
    {"code": "sn", "name": "Shona"},
    {"code": "so", "name": "Somali"},
    {"code": "so-DJ", "name": "Somali"},
    {"code": "so-ET", "name": "Somali"},
    {"code": "so-KE", "name": "Somali"},
    {"code": "sq", "name": "Albanian"},
    {"code": "sq-MK", "name": "Albanian"},
    {"code": "sq-XK", "name": "Albanian"},
    {"code": "sr", "name": "Serbian"},
    {"code": "sr-RS", "name": "Serbian"},
    {"code": "sr-Cyrl", "name": "Serbian"},
    {"code": "sr-Cyrl-BA", "name": "Serbian"},
    {"code": "sr-Cyrl-ME", "name": "Serbian"},
    {"code": "sr-Cyrl-XK", "name": "Serbian"},
    {"code": "sr-Latn", "name": "Serbian"},
    {"code": "sr-Latn-BA", "name": "Serbian"},
    {"code": "sr-Latn-ME", "name": "Serbian"},
    {"code": "sr-Latn-XK", "name": "Serbian"},
    {"code": "ss", "name": "Swati"},
    {"code": "ss-SZ", "name": "Swati"},
    {"code": "st", "name": "Southern Sotho"},
    {"code": "st-LS", "name": "Southern Sotho"},
    {"code": "su", "name": "Sundanese"},
    {"code": "su-Latn", "name": "Sundanese"},
    {"code": "sv", "name": "Swedish"},
    {"code": "sv-AX", "name": "Swedish"},
    {"code": "sv-FI", "name": "Swedish"},
    {"code": "sv-SE", "name": "Swedish"},
    {"code": "sw", "name": "Swahili"},
    {"code": "sw-CD", "name": "Swahili"},
    {"code": "sw-KE", "name": "Swahili"},
    {"code": "sw-TZ", "name": "Swahili"},
    {"code": "sw-UG", "name": "Swahili"},
    {"code": "ta", "name": "Tamil"},
    {"code": "ta-IN", "name": "Tamil"},
    {"code": "ta-LK", "name": "Tamil"},
    {"code": "ta-MY", "name": "Tamil"},
    {"code": "ta-SG", "name": "Tamil"},
    {"code": "te", "name": "Telugu"},
    {"code": "te-IN", "name": "Telugu"},
    {"code": "tg", "name": "Tajik"},
    {"code": "th", "name": "Thai"},
    {"code": "th-TH", "name": "Thai"},
    {"code": "ti", "name": "Tigrinya"},
    {"code": "ti-ER", "name": "Tigrinya"},
    {"code": "tk", "name": "Turkmen"},
    {"code": "tl", "name": "Tagalog"},
    {"code": "tn", "name": "Tswana"},
    {"code": "tn-BW", "name": "Tswana"},
    {"code": "to", "name": "Tonga"},
    {"code": "tr", "name": "Turkish"},
    {"code": "tr-CY", "name": "Turkish"},
    {"code": "tr-TR", "name": "Turkish"},
    {"code": "ts", "name": "Tsonga"},
    {"code": "tt", "name": "Tatar"},
    {"code": "ug", "name": "Uyghur"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "uk-UA", "name": "Ukrainian"},
    {"code": "ur", "name": "Urdu"},
    {"code": "ur-IN", "name": "Urdu"},
    {"code": "ur-PK", "name": "Urdu"},
    {"code": "uz", "name": "Uzbek"},
    {"code": "uz-Arab", "name": "Uzbek"},
    {"code": "uz-Cyrl", "name": "Uzbek"},
    {"code": "uz-Latn", "name": "Uzbek"},
    {"code": "ve", "name": "Venda"},
    {"code": "vi", "name": "Vietnamese"},
    {"code": "vi-VN", "name": "Vietnamese"},
    {"code": "vo", "name": "Volapük"},
    {"code": "wa", "name": "Walloon"},
    {"code": "wo", "name": "Wolof"},
    {"code": "xh", "name": "Xhosa"},
    {"code": "yi", "name": "Yiddish"},
    {"code": "yo", "name": "Yoruba"},
    {"code": "yo-BJ", "name": "Yoruba"},
    {"code": "za", "name": "Zhuang"},
    {"code": "zh", "name": "Chinese"},
    {"code": "zh-CH", "name": "Chinese"},
    {"code": "zh-TW", "name": "Chinese"},
    {"code": "zh-Hans", "name": "Chinese"},
    {"code": "zh-Hans-HK", "name": "Chinese"},
    {"code": "zh-Hans-MO", "name": "Chinese"},
    {"code": "zh-Hans-MY", "name": "Chinese"},
    {"code": "zh-Hans-SG", "name": "Chinese"},
    {"code": "zh-Hant", "name": "Chinese"},
    {"code": "zh-Hant-HK", "name": "Chinese"},
    {"code": "zh-Hant-MO", "name": "Chinese"},
    {"code": "zh-Hant-MY", "name": "Chinese"},
    {"code": "zh-Latn", "name": "Chinese"},
    {"code": "zu", "name": "Zulu"},
    {"code": "zu-ZA", "name": "Zulu"},
]


def _deduplicate_languages(raw_list: list[dict[str, str]]) -> list[dict[str, str]]:
    """
    Deduplicate languages by name, preferring shortest code.
    e.g. Arabic -> ar (over ar-AE, ar-EG)
    """
    grouped: dict[str, list[str]] = {}
    for lang in raw_list:
        name = lang["name"]
        code = lang["code"]
        if name not in grouped:
            grouped[name] = []
        grouped[name].append(code)
    
    deduplicated = []
    for name, codes in grouped.items():
        # Pick shortest code; if tie, sort alphabetically to be deterministic
        best_code = min(codes, key=lambda c: (len(c), c))
        deduplicated.append({"code": best_code, "name": name})
    
    return sorted(deduplicated, key=lambda x: x["name"])


TRANSLATEGEMMA_LANGUAGES = _deduplicate_languages(TRANSLATEGEMMA_RAW_LANGUAGES)

DEFAULT_SUPPORTED_LANGUAGES = QWEN_SUPPORTED_LANGUAGES

# Backward compatibility
SUPPORTED_LANGUAGES = DEFAULT_SUPPORTED_LANGUAGES
SOURCE_LANGUAGES = SUPPORTED_LANGUAGES
TARGET_LANGUAGES = SUPPORTED_LANGUAGES

# Global Map initialization
ALL_LANGUAGES_MAP = {l["code"]: l["name"] for l in QWEN_SUPPORTED_LANGUAGES}
# Add all raw TranslateGemma languages to support all codes
for l in TRANSLATEGEMMA_RAW_LANGUAGES:
    ALL_LANGUAGES_MAP[l["code"]] = l["name"]

CODE_TO_NAME = ALL_LANGUAGES_MAP

NAME_TO_CODE = {}
# Unified Name Lookup logic
_temp_name_to_codes = {}
# Add Qwen codes
for lang in QWEN_SUPPORTED_LANGUAGES:
    name_lower = lang["name"].lower()
    if name_lower not in _temp_name_to_codes:
        _temp_name_to_codes[name_lower] = []
    _temp_name_to_codes[name_lower].append(lang["code"])

# Add TranslateGemma codes
for lang in TRANSLATEGEMMA_RAW_LANGUAGES:
    name_lower = lang["name"].lower()
    if name_lower not in _temp_name_to_codes:
        _temp_name_to_codes[name_lower] = []
    if lang["code"] not in _temp_name_to_codes[name_lower]:
        _temp_name_to_codes[name_lower].append(lang["code"])

# Select best code for each name (prefer shortest)
for name_lower, codes in _temp_name_to_codes.items():
    NAME_TO_CODE[name_lower] = min(codes, key=lambda c: (len(c), c))


def get_supported_languages(model_name: str) -> list[dict[str, str]]:
    """Return the list of supported languages for the given model."""
    if "translategemma" in model_name.lower():
        return TRANSLATEGEMMA_LANGUAGES
    return DEFAULT_SUPPORTED_LANGUAGES


def get_language_name(code_or_name: str | list[str] | None) -> str:
    """
    Return the full language name for a given code or name.
    """
    if not code_or_name:
        return "English"

    if isinstance(code_or_name, list):
        for entry in code_or_name:
            if entry:
                return get_language_name(entry)
        return "English"

    # specific cache fix for "auto"
    if code_or_name.lower() == "auto":
        return "Auto"

    # If it's already a known name (case-insensitive check), return the proper casing
    lower_input = code_or_name.lower()
    if lower_input in NAME_TO_CODE:
        # It's a name, find the entry to get proper casing or just return input title-cased?
        # Better to return the value from CODE_TO_NAME using the code we found
        code = NAME_TO_CODE[lower_input]
        return CODE_TO_NAME.get(code, code_or_name.title())

    # If it's a code, return the name
    if code_or_name in CODE_TO_NAME:
        return CODE_TO_NAME[code_or_name]

    # Fallback: just return the input capitalized
    return code_or_name.title()


def get_language_code(name_or_code: str) -> str:
    """
    Return the ISO code for a given name or code.
    Defaults to 'en' if not found and input doesn't look like a code.
    """
    if not name_or_code:
        return "en"

    if name_or_code.lower() == "auto":
        return "auto"

    # If it's a known code
    if name_or_code in CODE_TO_NAME:
        return name_or_code

    # If it's a known name
    lower_input = name_or_code.lower()
    if lower_input in NAME_TO_CODE:
        return NAME_TO_CODE[lower_input]

    # If input is 2 chars, assume it's a code (fallback)
    if len(name_or_code) == 2:
        return name_or_code.lower()

    # Fallback default
    return "en"


def pick_language_name(*hints: str | list[str] | None) -> str:
    """
    Return the first resolvable language name from the provided hints.
    Hints may be ISO codes, human-readable names, comma-separated strings, or lists.
    Defaults to "Auto" when no hint can be resolved.
    """
    for hint in hints:
        if not hint:
            continue

        if isinstance(hint, list):
            for entry in hint:
                if entry:
                    return get_language_name(entry)
        elif isinstance(hint, str):
            first = hint.split(",")[0].strip()
            if first:
                return get_language_name(first)

    return "Auto"
